require "ifj21"
function fun0()
end

function fun1()
end

function fun2()
end

function fun3()
end

function fun4()
end

function fun5()
end

function fun6()
end

function fun7()
end

function fun8()
end

function fun9()
end

function fun10()
end

function fun11()
end

function fun12()
end

function fun13()
end

function fun14()
end

function fun15()
end

function fun16()
end

function fun17()
end

function fun18()
end

function fun19()
end

function fun20()
end

function fun21()
end

function fun22()
end

function fun23()
end

function fun24()
end

function fun25()
end

function fun26()
end

function fun27()
end

function fun28()
end

function fun29()
end

function fun30()
end

function fun31()
end

function fun32()
end

function fun33()
end

function fun34()
end

function fun35()
end

function fun36()
end

function fun37()
end

function fun38()
end

function fun39()
end

function fun40()
end

function fun41()
end

function fun42()
end

function fun43()
end

function fun44()
end

function fun45()
end

function fun46()
end

function fun47()
end

function fun48()
end

function fun49()
end

function fun50()
end

function fun51()
end

function fun52()
end

function fun53()
end

function fun54()
end

function fun55()
end

function fun56()
end

function fun57()
end

function fun58()
end

function fun59()
end

function fun60()
end

function fun61()
end

function fun62()
end

function fun63()
end

function fun64()
end

function fun65()
end

function fun66()
end

function fun67()
end

function fun68()
end

function fun69()
end

function fun70()
end

function fun71()
end

function fun72()
end

function fun73()
end

function fun74()
end

function fun75()
end

function fun76()
end

function fun77()
end

function fun78()
end

function fun79()
end

function fun80()
end

function fun81()
end

function fun82()
end

function fun83()
end

function fun84()
end

function fun85()
end

function fun86()
end

function fun87()
end

function fun88()
end

function fun89()
end

function fun90()
end

function fun91()
end

function fun92()
end

function fun93()
end

function fun94()
end

function fun95()
end

function fun96()
end

function fun97()
end

function fun98()
end

function fun99()
end

